### ISSUE TITLE
管理のカテゴリーに数字でる

### ISSUE THREAD

**Issue by codershisho** [codershisho/best-costume#20]
子メニューが数字になる。
再現できない・・・・。

![image](https://github.com/codershisho/best-costume/assets/120914888/ab04ad1f-4ef7-46af-916a-32faf60edfca)

**Comment by codershisho** [comment]
再現しない・・・。

**Comment by tk-kw** [comment]
![image](https://github.com/codershisho/best-costume/assets/72326243/e777afa2-0eb0-46a3-9aea-2276b4d38b65)
これイメージ見れるんすけ？ｗ

例えば
親:Womens、子:振袖選んだ後に親をMensにすると子が数値になる
かんじっす
